
package test.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WelcomeService", targetNamespace = "http://service.ws.hyacinth/", wsdlLocation = "http://localhost:8080/JaxwsSpringDemo/service/welcome?wsdl")
public class WelcomeService
    extends Service
{

    private final static URL WELCOMESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(test.ws.client.WelcomeService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = test.ws.client.WelcomeService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/JaxwsSpringDemo/service/welcome?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/JaxwsSpringDemo/service/welcome?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WELCOMESERVICE_WSDL_LOCATION = url;
    }

    public WelcomeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WelcomeService() {
        super(WELCOMESERVICE_WSDL_LOCATION, new QName("http://service.ws.hyacinth/", "WelcomeService"));
    }

    /**
     * 
     * @return
     *     returns Welcome
     */
    @WebEndpoint(name = "WelcomePort")
    public Welcome getWelcomePort() {
        return super.getPort(new QName("http://service.ws.hyacinth/", "WelcomePort"), Welcome.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Welcome
     */
    @WebEndpoint(name = "WelcomePort")
    public Welcome getWelcomePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.hyacinth/", "WelcomePort"), Welcome.class, features);
    }

}
